#' Import amplification data from QuantStudio & StepOne qPCR software
#'
#'import_amp() tidies the "Amplification Data" sheet of an .xls file produced by QuantStudio Design & Analysis Software v1.5.2 or StepOne Software v2.3.
#'
#' @param file character vector of length 1. Path to the .xls file containing the qPCR results to import.
#' @param from character vector of length 1. Indicates which qPCR software the input file originates from. Valid values are "QuantStudio" or "StepOne".
#'
#' @return A tibble with 4 columns: "well_position", "sample_id", "tar_nm", "cycle", "rn", and "delta_rn".
#'
#' @export
#'
#' @importFrom readxl read_excel
#' @importFrom stats setNames
#'
#' @examples
#'
import_amp <- function(file, from = "QuantStudio") {

  # Capture user's arguments

  file <- eval(expr = substitute(file), envir = parent.frame())

  from <- eval(expr = substitute(from), envir = parent.frame())

  # Stop execution in case of invalid input

  if (!requireNamespace("readxl", quietly = TRUE)) {
    warning("\nThe readxl package must be installed to use this function.\n")
    return(NULL)
  }

  if (!file.exists(file)) {
    stop("\nFile \"", file, "\" does not exist.\n")
  }

  if (length(from) != 1L || !from %in% c("QuantStudio", "StepOne")) {
    stop("\nfrom value must be \"QuantStudio\" or \"StepOne\".\n")
  }


  invalid_file <- vapply(X = c("Amplification Data", "Results"),
                         FUN = function(x) {
                           unique(class(try(expr = match(x = "Well",
                                                         table = suppressMessages(expr = read_excel(path = file,
                                                                                                    sheet = x))[[1]]),
                                            silent = T)) == "try-error") },
                         FUN.VALUE = vector(mode = "logical", length = 1L))

  if (any(invalid_file)) {
    stop("\nThe input file is not valid.\n")
  }

  skip <- vapply(X = c("Amplification Data", "Results"),
                 FUN = function(x) { match(x = "Well",
                                           table = suppressMessages(expr = read_excel(path = file,
                                                                                      sheet = x))[[1]]) },
                 FUN.VALUE = vector(mode = "integer", length = 1L))

  if (any(is.na(skip))) {
    stop("\nThe \"Results\" and/or \"Amplification Data\" sheet(s) in the input file do(es) not contain the required \"Well\" column.\n")
  }

  # Read qPCR results file

  amp_data <- suppressMessages(expr = read_excel(path = file,
                                                 sheet = "Amplification Data",
                                                 skip = skip[["Amplification Data"]]))

  sample_data <- suppressMessages(expr = read_excel(path = file,
                                                    sheet = "Results",
                                                    skip = skip[["Results"]]))

  # Tidy QuantStudio input

  if (from == "QuantStudio") {

    if (!all(c("Well Position", "Cycle", "Target Name", "Rn", "Delta Rn") %in% colnames(amp_data))) {
      if (all(c("Well", "Target Name", "Rn", paste0("\u0394", "Rn")) %in% colnames(amp_data))) {
        stop("\nThe \"Amplification Data\" sheet in the input file was generated by the StepOne software. Please provide from = \"StepOne\".\n")
      } else {
        stop("\nThe \"Amplification Data\" sheet in the input file does not contain one or more required column(s).\n")
      }
    }

    if (!all(c("Well Position", "Sample Name", "Target Name", "CT") %in% colnames(sample_data))) {
      stop("\nThe \"Results\" sheet in the input file does not contain one or more required column(s).\n")
    }

    amp_data <- setNames(object = amp_data[, c("Well Position", "Cycle", "Target Name", "Rn", "Delta Rn")],
                         nm = c("well_position", "cycle", "tar_nm", "rn", "delta_rn"))

    sample_data <- setNames(object = sample_data[, c("Well Position", "Sample Name", "Target Name")],
                            nm = c("well_position", "sample_id", "tar_nm"))

  }

  # Tidy StepOne input

  if (from == "StepOne") {

    if (!all(c("Well", "Target Name", "Rn", paste0("\u0394", "Rn")) %in% colnames(amp_data))) {
      if (all(c("Well Position", "Cycle", "Target Name", "Rn", "Delta Rn") %in% colnames(amp_data))) {
        stop("\nThe \"Amplification Data\" sheet in the input file was generated by the QuantStudio software. Please provide from = \"QuantStudio\".\n")
      } else {
        stop("\nThe \"Amplification Data\" sheet in the input file does not contain one or more required column(s).\n")
      }
    }

    if (!all(c("Well", "Sample Name", "Target Name", paste0("C", "\u1D1B")) %in% colnames(sample_data))) {
      stop("\nThe \"Results\" sheet in the input file does not contain one or more required column(s).\n")
    }

    amp_data <- setNames(object = amp_data[, c("Well", "Cycle", "Target Name", "Rn", paste0("\u0394", "Rn"))],
                         nm = c("well_position", "cycle", "tar_nm", "rn", "delta_rn"))

    sample_data <- setNames(object = sample_data[, c("Well", "Sample Name", "Target Name")],
                            nm = c("well_position", "sample_id", "tar_nm"))

  }

  # Merge amplification and sample ID data and tidy final output

  data <- merge(amp_data, sample_data, all = T)

  data <- data[!is.na(data$sample_id), c("well_position", "sample_id", "tar_nm", "cycle", "rn", "delta_rn")]

  data <- data[order(data$sample_id, data$tar_nm, data$cycle), , drop = F]

  return(data)

}
